### ISSUE TITLE
I want W801 support in IDE 

### ISSUE THREAD

**Issue by AnatolSher** [Hi-LinkDuino/w80x_arduino#27]
Hello! Is this project died? If NO, when you add W801?

**Comment by board707** [comment]
You can use this package with w801 board.
Select the W806 variant in the IDE - it compiled and works fine on W801 for me.
But the possibilities of this package are very modest.

**Comment by AnatolSher** [comment]
Yes! It work! Thank you.
I am using Arduino IDE 2.0.3 (win7-64). My problem was in the W801 ver 1.0 board. The RTS signal must be turned off. I dismantled the resistor R7. Now works well for me. Sorry for my English :)

**Comment by AnatolSher** [comment]
Hello again :)
One problem is solved.
Second: Under Linux (Centos 7-64b) and Arduino IDE compilation/linking error occurs- file not found... why?
see picture
![image](https://user-images.githubusercontent.com/121094544/215561998-fd69d8a0-c913-4f1e-b3c8-d376681091b2.png)

**Comment by board707** [comment]
Hello
I try to fix this. But it turned out not to be so easy. 
Firstly, in the package, the case of letters in file names is mixed up in some places. For windows this is not a problem, but in Linux it is not going to.
Secondly, the final build of the firmware in the Linux package is not configured.
Hope I will setup all in a couple of days.

**Comment by AnatolSher** [comment]
Thanks a lot! You are a great person!
A short summary of my research:
1) You must have two Arduino IDEs - old and new 2,0,3.
2) You need to upload the JSON file to the old version. After that, the devboard is available in the new version.
3) I made a debugger CKLink-Lite on a Chinese clone of STM32F103C8T6 (bluepill) with 256kb!!! flash on board. This works fine in the CDK for Windows. Question - how to make it work in Arduino IDE 2.0.3? Maybe you know?

**Comment by board707** [comment]
Try to install with using this json package file
`https://raw.githubusercontent.com/board707/w80x_arduino/linux_dev/package_w80x_index.json`

If you get a error during the compilation with `wm_tool` (like `lib64/libc.so.6: version GLIBC_2.34 not found`), go to the package tools directory `tools/w80x_tool/v1.0/lin` and copy wm_toold to wm_tool:
```
cp wm_toold wm_tool
```

**Comment by AnatolSher** [comment]
Hello!
Not worked :) 
![Screenshot from 2023-02-02 08-38-01](https://user-images.githubusercontent.com/121094544/216343464-d406c490-56de-4689-9e64-b358a3cddba6.png)

**Comment by board707** [comment]
Sorry, I has no ideas about this.
I have test it in two different PC without any errors...

**Comment by AnatolSher** [comment]
Magic?
![image](https://user-images.githubusercontent.com/121094544/216346066-882a7240-81b6-4309-aacc-a835d8f3d125.png)

under VirtualBox

**Comment by board707** [comment]
:) 
something like...

**Comment by AnatolSher** [comment]
Ok! I will climb Mount Everest for the second time :}
Maybe my ancient computer glitched. I have fresh :)

**Comment by board707** [comment]
I forked the repository to my github, [developing branch](https://github.com/board707/w80x_arduino/tree/linux_dev) is `linux_dev` 


I hope to continue developing it.
You can add the issues there.

**Comment by AnatolSher** [comment]
Of course. Thank you!

**Comment by AnatolSher** [comment]
Under Virtual Box flash programming OK!
![image](https://user-images.githubusercontent.com/121094544/216357746-90b87d9c-a807-4546-8f52-0108e35adc8c.png)
Config for COM port
![image](https://user-images.githubusercontent.com/121094544/216358512-8ee55515-7631-4cf8-9517-56b51b7a01dc.png)
