### ISSUE TITLE
下载之后程序不运行

### ISSUE THREAD

**Issue by songzhishuo** [Hi-LinkDuino/w80x_arduino#7]
我使用air103编译arduino代码下载之后代码不运行，对比了下海凌科的原理图发现ch340N的4脚接到了w806的RST上，好像arduino下载的时候不会去拉ch340N的RST# 引脚。这里要去看下下载脚本，是不是要主动去拉下RST#,让程序正常跑起来

**Comment by nulllaborg** [comment]
HLK的板子 串口DTR没有接 RST需要手动复位，但是也支持AT指令复位 不过目前版本没有加 这个软件指令复位功能
